export interface CanadianCity {
  name: string;
  province: string;
  slug: string;
}

export const PROVINCES_AND_TERRITORIES: Record<string, string> = {
  AB: "Alberta",
  BC: "British Columbia",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Newfoundland and Labrador",
  NS: "Nova Scotia",
  NT: "Northwest Territories",
  NU: "Nunavut",
  ON: "Ontario",
  PE: "Prince Edward Island",
  QC: "Quebec",
  SK: "Saskatchewan",
  YT: "Yukon",
};

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]/g, "");
}

function city(name: string, province: string): CanadianCity {
  return { name, province, slug: toSlug(name) };
}

export const CANADIAN_CITIES: CanadianCity[] = [
  // ===== Alberta (AB) =====
  city("Airdrie", "AB"),
  city("Athabasca", "AB"),
  city("Banff", "AB"),
  city("Barrhead", "AB"),
  city("Beaumont", "AB"),
  city("Bentley", "AB"),
  city("Black Diamond", "AB"),
  city("Blackfalds", "AB"),
  city("Bon Accord", "AB"),
  city("Bonnyville", "AB"),
  city("Bow Island", "AB"),
  city("Brooks", "AB"),
  city("Bruderheim", "AB"),
  city("Calgary", "AB"),
  city("Calmar", "AB"),
  city("Camrose", "AB"),
  city("Canmore", "AB"),
  city("Cardston", "AB"),
  city("Carstairs", "AB"),
  city("Chestermere", "AB"),
  city("Claresholm", "AB"),
  city("Coaldale", "AB"),
  city("Cochrane", "AB"),
  city("Cold Lake", "AB"),
  city("Crossfield", "AB"),
  city("Devon", "AB"),
  city("Didsbury", "AB"),
  city("Drayton Valley", "AB"),
  city("Drumheller", "AB"),
  city("Edmonton", "AB"),
  city("Edson", "AB"),
  city("Elk Point", "AB"),
  city("Fairview", "AB"),
  city("Fort Macleod", "AB"),
  city("Fort McMurray", "AB"),
  city("Fort Saskatchewan", "AB"),
  city("Gibbons", "AB"),
  city("Grande Cache", "AB"),
  city("Grande Prairie", "AB"),
  city("Grimshaw", "AB"),
  city("Hanna", "AB"),
  city("High Level", "AB"),
  city("High Prairie", "AB"),
  city("High River", "AB"),
  city("Hinton", "AB"),
  city("Innisfail", "AB"),
  city("Irricana", "AB"),
  city("Jasper", "AB"),
  city("Killam", "AB"),
  city("Lac La Biche", "AB"),
  city("Lacombe", "AB"),
  city("Lamont", "AB"),
  city("Leduc", "AB"),
  city("Legal", "AB"),
  city("Lethbridge", "AB"),
  city("Lloydminster", "AB"),
  city("Magrath", "AB"),
  city("Manning", "AB"),
  city("Mayerthorpe", "AB"),
  city("Medicine Hat", "AB"),
  city("Morinville", "AB"),
  city("Mundare", "AB"),
  city("Nanton", "AB"),
  city("Okotoks", "AB"),
  city("Olds", "AB"),
  city("Oyen", "AB"),
  city("Peace River", "AB"),
  city("Penhold", "AB"),
  city("Picture Butte", "AB"),
  city("Pincher Creek", "AB"),
  city("Ponoka", "AB"),
  city("Provost", "AB"),
  city("Raymond", "AB"),
  city("Red Deer", "AB"),
  city("Redcliff", "AB"),
  city("Redwater", "AB"),
  city("Rimbey", "AB"),
  city("Rocky Mountain House", "AB"),
  city("Sedgewick", "AB"),
  city("Sherwood Park", "AB"),
  city("Slave Lake", "AB"),
  city("Smoky Lake", "AB"),
  city("Spirit River", "AB"),
  city("Spruce Grove", "AB"),
  city("St. Albert", "AB"),
  city("Stettler", "AB"),
  city("Stony Plain", "AB"),
  city("Strathmore", "AB"),
  city("Sundre", "AB"),
  city("Swan Hills", "AB"),
  city("Sylvan Lake", "AB"),
  city("Taber", "AB"),
  city("Three Hills", "AB"),
  city("Tofield", "AB"),
  city("Trochu", "AB"),
  city("Turner Valley", "AB"),
  city("Two Hills", "AB"),
  city("Vegreville", "AB"),
  city("Vermilion", "AB"),
  city("Viking", "AB"),
  city("Vulcan", "AB"),
  city("Wainwright", "AB"),
  city("Westlock", "AB"),
  city("Wetaskiwin", "AB"),
  city("Whitecourt", "AB"),

  // ===== British Columbia (BC) =====
  city("Abbotsford", "BC"),
  city("Alert Bay", "BC"),
  city("Armstrong", "BC"),
  city("Burnaby", "BC"),
  city("Burns Lake", "BC"),
  city("Cache Creek", "BC"),
  city("Campbell River", "BC"),
  city("Castlegar", "BC"),
  city("Chase", "BC"),
  city("Chetwynd", "BC"),
  city("Chilliwack", "BC"),
  city("Clearwater", "BC"),
  city("Clinton", "BC"),
  city("Coldstream", "BC"),
  city("Colwood", "BC"),
  city("Comox", "BC"),
  city("Coquitlam", "BC"),
  city("Courtenay", "BC"),
  city("Cranbrook", "BC"),
  city("Creston", "BC"),
  city("Cumberland", "BC"),
  city("Dawson Creek", "BC"),
  city("Delta", "BC"),
  city("Duncan", "BC"),
  city("Elkford", "BC"),
  city("Enderby", "BC"),
  city("Esquimalt", "BC"),
  city("Fernie", "BC"),
  city("Fort Nelson", "BC"),
  city("Fort St. James", "BC"),
  city("Fort St. John", "BC"),
  city("Fraser Lake", "BC"),
  city("Fruitvale", "BC"),
  city("Gibsons", "BC"),
  city("Golden", "BC"),
  city("Grand Forks", "BC"),
  city("Greenwood", "BC"),
  city("Harrison Hot Springs", "BC"),
  city("Hope", "BC"),
  city("Houston", "BC"),
  city("Hudson's Hope", "BC"),
  city("Invermere", "BC"),
  city("Kamloops", "BC"),
  city("Kaslo", "BC"),
  city("Kelowna", "BC"),
  city("Kent", "BC"),
  city("Keremeos", "BC"),
  city("Kimberley", "BC"),
  city("Kitimat", "BC"),
  city("Ladysmith", "BC"),
  city("Lake Country", "BC"),
  city("Lake Cowichan", "BC"),
  city("Langford", "BC"),
  city("Langley", "BC"),
  city("Lillooet", "BC"),
  city("Lions Bay", "BC"),
  city("Logan Lake", "BC"),
  city("Lumby", "BC"),
  city("Lytton", "BC"),
  city("Mackenzie", "BC"),
  city("Maple Ridge", "BC"),
  city("McBride", "BC"),
  city("Merritt", "BC"),
  city("Metchosin", "BC"),
  city("Midway", "BC"),
  city("Mission", "BC"),
  city("Montrose", "BC"),
  city("Nakusp", "BC"),
  city("Nanaimo", "BC"),
  city("Nelson", "BC"),
  city("New Denver", "BC"),
  city("New Westminster", "BC"),
  city("North Cowichan", "BC"),
  city("North Saanich", "BC"),
  city("North Vancouver", "BC"),
  city("Oak Bay", "BC"),
  city("Oliver", "BC"),
  city("Osoyoos", "BC"),
  city("Parksville", "BC"),
  city("Peachland", "BC"),
  city("Pemberton", "BC"),
  city("Penticton", "BC"),
  city("Pitt Meadows", "BC"),
  city("Port Alberni", "BC"),
  city("Port Alice", "BC"),
  city("Port Clements", "BC"),
  city("Port Coquitlam", "BC"),
  city("Port Edward", "BC"),
  city("Port Hardy", "BC"),
  city("Port McNeill", "BC"),
  city("Port Moody", "BC"),
  city("Pouce Coupe", "BC"),
  city("Powell River", "BC"),
  city("Prince George", "BC"),
  city("Prince Rupert", "BC"),
  city("Princeton", "BC"),
  city("Qualicum Beach", "BC"),
  city("Quesnel", "BC"),
  city("Radium Hot Springs", "BC"),
  city("Revelstoke", "BC"),
  city("Richmond", "BC"),
  city("Rossland", "BC"),
  city("Saanich", "BC"),
  city("Salmo", "BC"),
  city("Salmon Arm", "BC"),
  city("Sayward", "BC"),
  city("Sechelt", "BC"),
  city("Sidney", "BC"),
  city("Silverton", "BC"),
  city("Smithers", "BC"),
  city("Sooke", "BC"),
  city("Sparwood", "BC"),
  city("Spallumcheen", "BC"),
  city("Squamish", "BC"),
  city("Stewart", "BC"),
  city("Summerland", "BC"),
  city("Sun Peaks", "BC"),
  city("Surrey", "BC"),
  city("Tahsis", "BC"),
  city("Taylor", "BC"),
  city("Telkwa", "BC"),
  city("Terrace", "BC"),
  city("Tofino", "BC"),
  city("Trail", "BC"),
  city("Tumbler Ridge", "BC"),
  city("Ucluelet", "BC"),
  city("Valemount", "BC"),
  city("Vancouver", "BC"),
  city("Vanderhoof", "BC"),
  city("Vernon", "BC"),
  city("Victoria", "BC"),
  city("View Royal", "BC"),
  city("Warfield", "BC"),
  city("Wells", "BC"),
  city("West Kelowna", "BC"),
  city("West Vancouver", "BC"),
  city("Whistler", "BC"),
  city("White Rock", "BC"),
  city("Williams Lake", "BC"),
  city("Zeballos", "BC"),

  // ===== Manitoba (MB) =====
  city("Altona", "MB"),
  city("Beausejour", "MB"),
  city("Birtle", "MB"),
  city("Boissevain", "MB"),
  city("Brandon", "MB"),
  city("Carberry", "MB"),
  city("Carman", "MB"),
  city("Churchill", "MB"),
  city("Dauphin", "MB"),
  city("Deloraine", "MB"),
  city("Flin Flon", "MB"),
  city("Gimli", "MB"),
  city("Gladstone", "MB"),
  city("Grandview", "MB"),
  city("Hamiota", "MB"),
  city("Killarney", "MB"),
  city("Lac du Bonnet", "MB"),
  city("Leaf Rapids", "MB"),
  city("Lynn Lake", "MB"),
  city("MacGregor", "MB"),
  city("Manitou", "MB"),
  city("Melita", "MB"),
  city("Minitonas", "MB"),
  city("Minnedosa", "MB"),
  city("Morden", "MB"),
  city("Morris", "MB"),
  city("Neepawa", "MB"),
  city("Niverville", "MB"),
  city("Oakbank", "MB"),
  city("Pilot Mound", "MB"),
  city("Pinawa", "MB"),
  city("Pine Falls", "MB"),
  city("Portage la Prairie", "MB"),
  city("Roblin", "MB"),
  city("Rossburn", "MB"),
  city("Russell", "MB"),
  city("Selkirk", "MB"),
  city("Snow Lake", "MB"),
  city("Souris", "MB"),
  city("St. Pierre-Jolys", "MB"),
  city("Steinbach", "MB"),
  city("Stonewall", "MB"),
  city("Swan River", "MB"),
  city("Teulon", "MB"),
  city("The Pas", "MB"),
  city("Thompson", "MB"),
  city("Virden", "MB"),
  city("Winkler", "MB"),
  city("Winnipeg", "MB"),
  city("Winnipeg Beach", "MB"),

  // ===== New Brunswick (NB) =====
  city("Bathurst", "NB"),
  city("Bouctouche", "NB"),
  city("Campbellton", "NB"),
  city("Caraquet", "NB"),
  city("Dalhousie", "NB"),
  city("Dieppe", "NB"),
  city("Edmundston", "NB"),
  city("Florenceville-Bristol", "NB"),
  city("Fredericton", "NB"),
  city("Grand Bay-Westfield", "NB"),
  city("Grand Falls", "NB"),
  city("Hampton", "NB"),
  city("Hartland", "NB"),
  city("Hillsborough", "NB"),
  city("Kedgwick", "NB"),
  city("Miramichi", "NB"),
  city("Moncton", "NB"),
  city("Nackawic", "NB"),
  city("New Maryland", "NB"),
  city("Oromocto", "NB"),
  city("Perth-Andover", "NB"),
  city("Petit-Rocher", "NB"),
  city("Quispamsis", "NB"),
  city("Rexton", "NB"),
  city("Richibucto", "NB"),
  city("Riverview", "NB"),
  city("Rothesay", "NB"),
  city("Sackville", "NB"),
  city("Saint John", "NB"),
  city("Saint-Leonard", "NB"),
  city("Saint-Quentin", "NB"),
  city("Shediac", "NB"),
  city("Shippagan", "NB"),
  city("St. Andrews", "NB"),
  city("St. George", "NB"),
  city("St. Stephen", "NB"),
  city("Sussex", "NB"),
  city("Tracadie-Sheila", "NB"),
  city("Woodstock", "NB"),

  // ===== Newfoundland and Labrador (NL) =====
  city("Bay Roberts", "NL"),
  city("Bishop's Falls", "NL"),
  city("Bonavista", "NL"),
  city("Botwood", "NL"),
  city("Burgeo", "NL"),
  city("Carbonear", "NL"),
  city("Carmanville", "NL"),
  city("Channel-Port aux Basques", "NL"),
  city("Clarenville", "NL"),
  city("Conception Bay South", "NL"),
  city("Corner Brook", "NL"),
  city("Deer Lake", "NL"),
  city("Fogo Island", "NL"),
  city("Gander", "NL"),
  city("Grand Bank", "NL"),
  city("Grand Falls-Windsor", "NL"),
  city("Happy Valley-Goose Bay", "NL"),
  city("Harbour Breton", "NL"),
  city("Harbour Grace", "NL"),
  city("Holyrood", "NL"),
  city("Labrador City", "NL"),
  city("Lewisporte", "NL"),
  city("Marystown", "NL"),
  city("Mount Pearl", "NL"),
  city("Paradise", "NL"),
  city("Pasadena", "NL"),
  city("Placentia", "NL"),
  city("Portugal Cove-St. Philip's", "NL"),
  city("Springdale", "NL"),
  city("St. Anthony", "NL"),
  city("St. John's", "NL"),
  city("Stephenville", "NL"),
  city("Stephenville Crossing", "NL"),
  city("Torbay", "NL"),
  city("Twillingate", "NL"),
  city("Upper Island Cove", "NL"),
  city("Wabush", "NL"),

  // ===== Nova Scotia (NS) =====
  city("Amherst", "NS"),
  city("Annapolis Royal", "NS"),
  city("Antigonish", "NS"),
  city("Berwick", "NS"),
  city("Bridgewater", "NS"),
  city("Canso", "NS"),
  city("Chester", "NS"),
  city("Clark's Harbour", "NS"),
  city("Dartmouth", "NS"),
  city("Digby", "NS"),
  city("Dominion", "NS"),
  city("Glace Bay", "NS"),
  city("Halifax", "NS"),
  city("Hantsport", "NS"),
  city("Inverness", "NS"),
  city("Kentville", "NS"),
  city("Liverpool", "NS"),
  city("Lockeport", "NS"),
  city("Louisbourg", "NS"),
  city("Lunenburg", "NS"),
  city("Mahone Bay", "NS"),
  city("Middleton", "NS"),
  city("Mulgrave", "NS"),
  city("New Glasgow", "NS"),
  city("New Waterford", "NS"),
  city("North Sydney", "NS"),
  city("Oxford", "NS"),
  city("Parrsboro", "NS"),
  city("Pictou", "NS"),
  city("Port Hawkesbury", "NS"),
  city("Shelburne", "NS"),
  city("Springhill", "NS"),
  city("Stellarton", "NS"),
  city("Stewiacke", "NS"),
  city("Sydney", "NS"),
  city("Sydney Mines", "NS"),
  city("Tatamagouche", "NS"),
  city("Trenton", "NS"),
  city("Truro", "NS"),
  city("Westville", "NS"),
  city("Windsor", "NS"),
  city("Wolfville", "NS"),
  city("Yarmouth", "NS"),

  // ===== Northwest Territories (NT) =====
  city("Behchoko", "NT"),
  city("Fort Liard", "NT"),
  city("Fort Providence", "NT"),
  city("Fort Resolution", "NT"),
  city("Fort Simpson", "NT"),
  city("Fort Smith", "NT"),
  city("Hay River", "NT"),
  city("Inuvik", "NT"),
  city("Norman Wells", "NT"),
  city("Tuktoyaktuk", "NT"),
  city("Yellowknife", "NT"),

  // ===== Nunavut (NU) =====
  city("Arviat", "NU"),
  city("Baker Lake", "NU"),
  city("Cambridge Bay", "NU"),
  city("Cape Dorset", "NU"),
  city("Gjoa Haven", "NU"),
  city("Igloolik", "NU"),
  city("Iqaluit", "NU"),
  city("Kugluktuk", "NU"),
  city("Pangnirtung", "NU"),
  city("Pond Inlet", "NU"),
  city("Rankin Inlet", "NU"),

  // ===== Ontario (ON) =====
  city("Ajax", "ON"),
  city("Alexandria", "ON"),
  city("Alfred and Plantagenet", "ON"),
  city("Alliston", "ON"),
  city("Almonte", "ON"),
  city("Amherstburg", "ON"),
  city("Arnprior", "ON"),
  city("Atikokan", "ON"),
  city("Aurora", "ON"),
  city("Aylmer", "ON"),
  city("Bancroft", "ON"),
  city("Barrie", "ON"),
  city("Barry's Bay", "ON"),
  city("Bath", "ON"),
  city("Belleville", "ON"),
  city("Blind River", "ON"),
  city("Bluewater", "ON"),
  city("Bonfield", "ON"),
  city("Bracebridge", "ON"),
  city("Bradford West Gwillimbury", "ON"),
  city("Brampton", "ON"),
  city("Brant", "ON"),
  city("Brantford", "ON"),
  city("Brock", "ON"),
  city("Brockville", "ON"),
  city("Burlington", "ON"),
  city("Caledon", "ON"),
  city("Cambridge", "ON"),
  city("Carleton Place", "ON"),
  city("Casselman", "ON"),
  city("Central Elgin", "ON"),
  city("Centre Wellington", "ON"),
  city("Champlain", "ON"),
  city("Chapleau", "ON"),
  city("Chatham-Kent", "ON"),
  city("Clarence-Rockland", "ON"),
  city("Clarington", "ON"),
  city("Clinton", "ON"),
  city("Cobalt", "ON"),
  city("Cobourg", "ON"),
  city("Cochrane", "ON"),
  city("Collingwood", "ON"),
  city("Cornwall", "ON"),
  city("Deep River", "ON"),
  city("Deseronto", "ON"),
  city("Dorchester", "ON"),
  city("Dryden", "ON"),
  city("Dundas", "ON"),
  city("Dunnville", "ON"),
  city("Durham", "ON"),
  city("Dutton-Dunwich", "ON"),
  city("Ear Falls", "ON"),
  city("East Gwillimbury", "ON"),
  city("East Zorra-Tavistock", "ON"),
  city("Edwardsburgh-Cardinal", "ON"),
  city("Elliot Lake", "ON"),
  city("Emo", "ON"),
  city("Englehart", "ON"),
  city("Erin", "ON"),
  city("Espanola", "ON"),
  city("Essa", "ON"),
  city("Essex", "ON"),
  city("Fergus", "ON"),
  city("Fort Erie", "ON"),
  city("Fort Frances", "ON"),
  city("Gananoque", "ON"),
  city("Georgina", "ON"),
  city("Goderich", "ON"),
  city("Gore Bay", "ON"),
  city("Gravenhurst", "ON"),
  city("Greater Napanee", "ON"),
  city("Greenstone", "ON"),
  city("Grimsby", "ON"),
  city("Guelph", "ON"),
  city("Guelph-Eramosa", "ON"),
  city("Haldimand County", "ON"),
  city("Halton Hills", "ON"),
  city("Hamilton", "ON"),
  city("Hanover", "ON"),
  city("Hastings Highlands", "ON"),
  city("Hawkesbury", "ON"),
  city("Hearst", "ON"),
  city("Hornepayne", "ON"),
  city("Huntsville", "ON"),
  city("Huron East", "ON"),
  city("Ingersoll", "ON"),
  city("Innisfil", "ON"),
  city("Iroquois Falls", "ON"),
  city("Kapuskasing", "ON"),
  city("Kearney", "ON"),
  city("Kemptville", "ON"),
  city("Kenora", "ON"),
  city("Kincardine", "ON"),
  city("King", "ON"),
  city("Kingston", "ON"),
  city("Kingsville", "ON"),
  city("Kirkland Lake", "ON"),
  city("Kitchener", "ON"),
  city("Lakeshore", "ON"),
  city("Lambton Shores", "ON"),
  city("LaSalle", "ON"),
  city("Laurentian Valley", "ON"),
  city("Leamington", "ON"),
  city("Lincoln", "ON"),
  city("Lindsay", "ON"),
  city("Listowel", "ON"),
  city("London", "ON"),
  city("Loyalist", "ON"),
  city("Lucan Biddulph", "ON"),
  city("Madawaska Valley", "ON"),
  city("Madoc", "ON"),
  city("Mapleton", "ON"),
  city("Marathon", "ON"),
  city("Markham", "ON"),
  city("Marmora and Lake", "ON"),
  city("Mattawa", "ON"),
  city("Meaford", "ON"),
  city("Midland", "ON"),
  city("Milton", "ON"),
  city("Minto", "ON"),
  city("Mississauga", "ON"),
  city("Mississippi Mills", "ON"),
  city("Mono", "ON"),
  city("Moonbeam", "ON"),
  city("Moosonee", "ON"),
  city("Morris-Turnberry", "ON"),
  city("Mount Forest", "ON"),
  city("Muskoka Lakes", "ON"),
  city("New Tecumseth", "ON"),
  city("Newmarket", "ON"),
  city("Niagara Falls", "ON"),
  city("Niagara-on-the-Lake", "ON"),
  city("Nipigon", "ON"),
  city("Norfolk County", "ON"),
  city("North Bay", "ON"),
  city("North Dundas", "ON"),
  city("North Frontenac", "ON"),
  city("North Glengarry", "ON"),
  city("North Grenville", "ON"),
  city("North Perth", "ON"),
  city("North Stormont", "ON"),
  city("Norwich", "ON"),
  city("Oakville", "ON"),
  city("Orangeville", "ON"),
  city("Orillia", "ON"),
  city("Oro-Medonte", "ON"),
  city("Oshawa", "ON"),
  city("Ottawa", "ON"),
  city("Owen Sound", "ON"),
  city("Parry Sound", "ON"),
  city("Pelham", "ON"),
  city("Pembroke", "ON"),
  city("Penetanguishene", "ON"),
  city("Perth", "ON"),
  city("Perth East", "ON"),
  city("Petawawa", "ON"),
  city("Peterborough", "ON"),
  city("Petrolia", "ON"),
  city("Pickering", "ON"),
  city("Plympton-Wyoming", "ON"),
  city("Point Edward", "ON"),
  city("Port Colborne", "ON"),
  city("Port Hope", "ON"),
  city("Prescott", "ON"),
  city("Prince Edward County", "ON"),
  city("Puslinch", "ON"),
  city("Quinte West", "ON"),
  city("Rainy River", "ON"),
  city("Ramara", "ON"),
  city("Red Lake", "ON"),
  city("Renfrew", "ON"),
  city("Richmond Hill", "ON"),
  city("Rideau Lakes", "ON"),
  city("Russell", "ON"),
  city("Sarnia", "ON"),
  city("Saugeen Shores", "ON"),
  city("Sault Ste. Marie", "ON"),
  city("Scugog", "ON"),
  city("Severn", "ON"),
  city("Shelburne", "ON"),
  city("Sioux Lookout", "ON"),
  city("Smiths Falls", "ON"),
  city("South Bruce Peninsula", "ON"),
  city("South Dundas", "ON"),
  city("South Frontenac", "ON"),
  city("South Glengarry", "ON"),
  city("South Huron", "ON"),
  city("South Stormont", "ON"),
  city("Southgate", "ON"),
  city("Southwest Middlesex", "ON"),
  city("Spanish", "ON"),
  city("Springwater", "ON"),
  city("St. Catharines", "ON"),
  city("St. Marys", "ON"),
  city("St. Thomas", "ON"),
  city("Stirling-Rawdon", "ON"),
  city("Stratford", "ON"),
  city("Strathroy-Caradoc", "ON"),
  city("Sudbury", "ON"),
  city("Tay", "ON"),
  city("Tecumseh", "ON"),
  city("Temiskaming Shores", "ON"),
  city("Thames Centre", "ON"),
  city("The Blue Mountains", "ON"),
  city("Thorold", "ON"),
  city("Thunder Bay", "ON"),
  city("Tillsonburg", "ON"),
  city("Timmins", "ON"),
  city("Tiny", "ON"),
  city("Toronto", "ON"),
  city("Trent Hills", "ON"),
  city("Trent Lakes", "ON"),
  city("Tweed", "ON"),
  city("Uxbridge", "ON"),
  city("Vaughan", "ON"),
  city("Wainfleet", "ON"),
  city("Wasaga Beach", "ON"),
  city("Waterloo", "ON"),
  city("Welland", "ON"),
  city("Wellington North", "ON"),
  city("West Elgin", "ON"),
  city("West Lincoln", "ON"),
  city("West Nipissing", "ON"),
  city("West Perth", "ON"),
  city("Whitby", "ON"),
  city("Whitchurch-Stouffville", "ON"),
  city("Wilmot", "ON"),
  city("Windsor", "ON"),
  city("Woodstock", "ON"),
  city("Woolwich", "ON"),
  city("Zorra", "ON"),

  // ===== Prince Edward Island (PE) =====
  city("Alberton", "PE"),
  city("Borden-Carleton", "PE"),
  city("Charlottetown", "PE"),
  city("Cornwall", "PE"),
  city("Georgetown", "PE"),
  city("Kensington", "PE"),
  city("Montague", "PE"),
  city("Morell", "PE"),
  city("Murray Harbour", "PE"),
  city("O'Leary", "PE"),
  city("Souris", "PE"),
  city("Stratford", "PE"),
  city("Summerside", "PE"),
  city("Tignish", "PE"),

  // ===== Quebec (QC) =====
  city("Acton Vale", "QC"),
  city("Alma", "QC"),
  city("Amos", "QC"),
  city("Amqui", "QC"),
  city("Asbestos", "QC"),
  city("Baie-Comeau", "QC"),
  city("Baie-D'Urfe", "QC"),
  city("Baie-Saint-Paul", "QC"),
  city("Barkmere", "QC"),
  city("Beaconsfield", "QC"),
  city("Beauceville", "QC"),
  city("Beauharnois", "QC"),
  city("Beaupre", "QC"),
  city("Becancour", "QC"),
  city("Bedford", "QC"),
  city("Beloeil", "QC"),
  city("Berthierville", "QC"),
  city("Blainville", "QC"),
  city("Boisbriand", "QC"),
  city("Bois-des-Filion", "QC"),
  city("Boucherville", "QC"),
  city("Bromont", "QC"),
  city("Brossard", "QC"),
  city("Brownsburg-Chatham", "QC"),
  city("Candiac", "QC"),
  city("Cap-Chat", "QC"),
  city("Cap-Sante", "QC"),
  city("Carignan", "QC"),
  city("Carleton-sur-Mer", "QC"),
  city("Chambly", "QC"),
  city("Chandler", "QC"),
  city("Chapais", "QC"),
  city("Charlemagne", "QC"),
  city("Chateauguay", "QC"),
  city("Chelsea", "QC"),
  city("Chibougamau", "QC"),
  city("Clermont", "QC"),
  city("Coaticook", "QC"),
  city("Contrecoeur", "QC"),
  city("Cookshire-Eaton", "QC"),
  city("Cote-Saint-Luc", "QC"),
  city("Coteau-du-Lac", "QC"),
  city("Cowansville", "QC"),
  city("Danville", "QC"),
  city("Daveluyville", "QC"),
  city("Delson", "QC"),
  city("Desbiens", "QC"),
  city("Deux-Montagnes", "QC"),
  city("Disraeli", "QC"),
  city("Dolbeau-Mistassini", "QC"),
  city("Dollard-des-Ormeaux", "QC"),
  city("Donnacona", "QC"),
  city("Dorval", "QC"),
  city("Drummondville", "QC"),
  city("Dunham", "QC"),
  city("East Angus", "QC"),
  city("Farnham", "QC"),
  city("Fermont", "QC"),
  city("Forestville", "QC"),
  city("Gaspe", "QC"),
  city("Gatineau", "QC"),
  city("Gracefield", "QC"),
  city("Granby", "QC"),
  city("Hampstead", "QC"),
  city("Hudson", "QC"),
  city("Huntingdon", "QC"),
  city("Joliette", "QC"),
  city("Kingsey Falls", "QC"),
  city("Kirkland", "QC"),
  city("La Malbaie", "QC"),
  city("La Pocatiere", "QC"),
  city("La Prairie", "QC"),
  city("La Sarre", "QC"),
  city("La Tuque", "QC"),
  city("Lac-Brome", "QC"),
  city("Lac-Delage", "QC"),
  city("Lac-Megantic", "QC"),
  city("Lac-Saint-Joseph", "QC"),
  city("Lachute", "QC"),
  city("L'Ancienne-Lorette", "QC"),
  city("L'Assomption", "QC"),
  city("Laval", "QC"),
  city("Lavaltrie", "QC"),
  city("Le Bic", "QC"),
  city("Lebel-sur-Quevillon", "QC"),
  city("L'Epiphanie", "QC"),
  city("Les Cedres", "QC"),
  city("Les Coteaux", "QC"),
  city("Levis", "QC"),
  city("L'Ile-Perrot", "QC"),
  city("Longueuil", "QC"),
  city("Lorraine", "QC"),
  city("Louiseville", "QC"),
  city("Macamic", "QC"),
  city("Magog", "QC"),
  city("Malartic", "QC"),
  city("Maniwaki", "QC"),
  city("Marieville", "QC"),
  city("Mascouche", "QC"),
  city("Matagami", "QC"),
  city("Matane", "QC"),
  city("Mercier", "QC"),
  city("Metabetchouan-Lac-a-la-Croix", "QC"),
  city("Mirabel", "QC"),
  city("Mont-Joli", "QC"),
  city("Mont-Laurier", "QC"),
  city("Mont-Royal", "QC"),
  city("Mont-Saint-Hilaire", "QC"),
  city("Mont-Tremblant", "QC"),
  city("Montmagny", "QC"),
  city("Montreal", "QC"),
  city("Montreal-Est", "QC"),
  city("Montreal-Ouest", "QC"),
  city("Murdochville", "QC"),
  city("Neuville", "QC"),
  city("New Richmond", "QC"),
  city("Nicolet", "QC"),
  city("Normandin", "QC"),
  city("Notre-Dame-de-l'Ile-Perrot", "QC"),
  city("Notre-Dame-des-Prairies", "QC"),
  city("Otterburn Park", "QC"),
  city("Paspebiac", "QC"),
  city("Perce", "QC"),
  city("Pincourt", "QC"),
  city("Plessisville", "QC"),
  city("Pointe-Claire", "QC"),
  city("Pont-Rouge", "QC"),
  city("Port-Cartier", "QC"),
  city("Portneuf", "QC"),
  city("Prevost", "QC"),
  city("Princeville", "QC"),
  city("Quebec City", "QC"),
  city("Rawdon", "QC"),
  city("Repentigny", "QC"),
  city("Richmond", "QC"),
  city("Rigaud", "QC"),
  city("Rimouski", "QC"),
  city("Riviere-du-Loup", "QC"),
  city("Riviere-Rouge", "QC"),
  city("Roberval", "QC"),
  city("Rosemere", "QC"),
  city("Rougemont", "QC"),
  city("Rouyn-Noranda", "QC"),
  city("Saguenay", "QC"),
  city("Saint-Amable", "QC"),
  city("Saint-Augustin-de-Desmaures", "QC"),
  city("Saint-Basile-le-Grand", "QC"),
  city("Saint-Bruno-de-Montarville", "QC"),
  city("Saint-Cesaire", "QC"),
  city("Saint-Charles-Borromee", "QC"),
  city("Saint-Colomban", "QC"),
  city("Saint-Constant", "QC"),
  city("Saint-Eustache", "QC"),
  city("Saint-Felicien", "QC"),
  city("Saint-Gabriel", "QC"),
  city("Saint-Georges", "QC"),
  city("Saint-Germain-de-Grantham", "QC"),
  city("Saint-Hyacinthe", "QC"),
  city("Saint-Jean-sur-Richelieu", "QC"),
  city("Saint-Jerome", "QC"),
  city("Saint-Joseph-de-Beauce", "QC"),
  city("Saint-Joseph-de-Sorel", "QC"),
  city("Saint-Joseph-du-Lac", "QC"),
  city("Saint-Lambert", "QC"),
  city("Saint-Lazare", "QC"),
  city("Saint-Lin-Laurentides", "QC"),
  city("Saint-Marc-des-Carrieres", "QC"),
  city("Saint-Ours", "QC"),
  city("Saint-Pamphile", "QC"),
  city("Saint-Pascal", "QC"),
  city("Saint-Paul", "QC"),
  city("Saint-Pie", "QC"),
  city("Saint-Raymond", "QC"),
  city("Saint-Remi", "QC"),
  city("Saint-Sauveur", "QC"),
  city("Saint-Tite", "QC"),
  city("Saint-Zotique", "QC"),
  city("Sainte-Adele", "QC"),
  city("Sainte-Agathe-des-Monts", "QC"),
  city("Sainte-Anne-de-Bellevue", "QC"),
  city("Sainte-Anne-des-Monts", "QC"),
  city("Sainte-Anne-des-Plaines", "QC"),
  city("Sainte-Catherine", "QC"),
  city("Sainte-Catherine-de-la-Jacques-Cartier", "QC"),
  city("Sainte-Julie", "QC"),
  city("Sainte-Julienne", "QC"),
  city("Sainte-Marie", "QC"),
  city("Sainte-Marthe-sur-le-Lac", "QC"),
  city("Sainte-Sophie", "QC"),
  city("Sainte-Therese", "QC"),
  city("Salaberry-de-Valleyfield", "QC"),
  city("Schefferville", "QC"),
  city("Scotstown", "QC"),
  city("Senneterre", "QC"),
  city("Sept-Iles", "QC"),
  city("Shannon", "QC"),
  city("Shawinigan", "QC"),
  city("Sherbrooke", "QC"),
  city("Sorel-Tracy", "QC"),
  city("Stoneham-et-Tewkesbury", "QC"),
  city("Sutton", "QC"),
  city("Temiscaming", "QC"),
  city("Terrebonne", "QC"),
  city("Thetford Mines", "QC"),
  city("Thurso", "QC"),
  city("Trois-Pistoles", "QC"),
  city("Trois-Rivieres", "QC"),
  city("Val-David", "QC"),
  city("Val-des-Monts", "QC"),
  city("Val-d'Or", "QC"),
  city("Val-Morin", "QC"),
  city("Varennes", "QC"),
  city("Vaudreuil-Dorion", "QC"),
  city("Victoriaville", "QC"),
  city("Ville-Marie", "QC"),
  city("Warwick", "QC"),
  city("Waterloo", "QC"),
  city("Waterville", "QC"),
  city("Westmount", "QC"),
  city("Windsor", "QC"),

  // ===== Saskatchewan (SK) =====
  city("Assiniboia", "SK"),
  city("Battleford", "SK"),
  city("Biggar", "SK"),
  city("Canora", "SK"),
  city("Carlyle", "SK"),
  city("Craik", "SK"),
  city("Creighton", "SK"),
  city("Esterhazy", "SK"),
  city("Estevan", "SK"),
  city("Foam Lake", "SK"),
  city("Fort Qu'Appelle", "SK"),
  city("Gravelbourg", "SK"),
  city("Humboldt", "SK"),
  city("Indian Head", "SK"),
  city("Kamsack", "SK"),
  city("Kerrobert", "SK"),
  city("Kindersley", "SK"),
  city("La Ronge", "SK"),
  city("Langenburg", "SK"),
  city("Langham", "SK"),
  city("Lanigan", "SK"),
  city("Lloydminster", "SK"),
  city("Lumsden", "SK"),
  city("Macklin", "SK"),
  city("Maple Creek", "SK"),
  city("Martensville", "SK"),
  city("Meadow Lake", "SK"),
  city("Melfort", "SK"),
  city("Melville", "SK"),
  city("Moose Jaw", "SK"),
  city("Moosomin", "SK"),
  city("Nipawin", "SK"),
  city("North Battleford", "SK"),
  city("Outlook", "SK"),
  city("Oxbow", "SK"),
  city("Pilot Butte", "SK"),
  city("Preeceville", "SK"),
  city("Prince Albert", "SK"),
  city("Regina", "SK"),
  city("Rosetown", "SK"),
  city("Rosthern", "SK"),
  city("Saskatoon", "SK"),
  city("Shaunavon", "SK"),
  city("Shellbrook", "SK"),
  city("Swift Current", "SK"),
  city("Tisdale", "SK"),
  city("Unity", "SK"),
  city("Wadena", "SK"),
  city("Warman", "SK"),
  city("Watrous", "SK"),
  city("Weyburn", "SK"),
  city("White City", "SK"),
  city("Whitewood", "SK"),
  city("Wynyard", "SK"),
  city("Yorkton", "SK"),

  // ===== Yukon (YT) =====
  city("Carmacks", "YT"),
  city("Dawson City", "YT"),
  city("Faro", "YT"),
  city("Haines Junction", "YT"),
  city("Mayo", "YT"),
  city("Teslin", "YT"),
  city("Watson Lake", "YT"),
  city("Whitehorse", "YT"),
].sort((a, b) => {
  if (a.province < b.province) return -1;
  if (a.province > b.province) return 1;
  if (a.name < b.name) return -1;
  if (a.name > b.name) return 1;
  return 0;
});

/**
 * Search cities by name. Prefix matches are prioritized over substring matches.
 * Returns at most `limit` results.
 */
export function searchCities(query: string, limit = 20): CanadianCity[] {
  if (!query || query.trim().length === 0) return [];

  const q = query.toLowerCase().trim();

  const prefixMatches: CanadianCity[] = [];
  const substringMatches: CanadianCity[] = [];

  for (const city of CANADIAN_CITIES) {
    const lowerName = city.name.toLowerCase();
    if (lowerName.startsWith(q)) {
      prefixMatches.push(city);
    } else if (lowerName.includes(q)) {
      substringMatches.push(city);
    }
  }

  return [...prefixMatches, ...substringMatches].slice(0, limit);
}

/**
 * Find a city by its URL-friendly slug.
 */
export function getCityBySlug(slug: string): CanadianCity | undefined {
  if (!slug) return undefined;
  const normalised = slug.toLowerCase().trim();
  return CANADIAN_CITIES.find((c) => c.slug === normalised);
}

/**
 * Get all cities for a given province/territory code (e.g. "ON").
 */
export function getCitiesByProvince(province: string): CanadianCity[] {
  if (!province) return [];
  const code = province.toUpperCase().trim();
  return CANADIAN_CITIES.filter((c) => c.province === code);
}

/**
 * Format a city as "CityName, ProvinceCode" e.g. "Hamilton, ON".
 */
export function formatCityProvince(city: CanadianCity): string {
  return `${city.name}, ${city.province}`;
}

/**
 * Normalize a service-area string to a canonical slug.
 * First tries exact slug lookup in the city database;
 * falls back to raw slugification so legacy free-text entries
 * still produce a reasonable slug.
 */
export function normalizeServiceAreaSlug(area: string): string {
  if (!area) return "";
  const slug = area
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]/g, "");

  // Check if the slug matches a canonical city
  const canonical = getCityBySlug(slug);
  if (canonical) return canonical.slug;

  // Try matching by city name (case-insensitive) for legacy entries
  const byName = CANADIAN_CITIES.find(
    (c) => c.name.toLowerCase() === area.toLowerCase().trim()
  );
  if (byName) return byName.slug;

  // Fallback: return the raw slug
  return slug;
}
